"""initial_standard_metadata_tables

Revision ID: 587f20556e83
Revises: 
Create Date: 2026-03-25 23:09:25.258998
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '587f20556e83'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_classification',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True, comment='상위 분류'),
    sa.Column('level', sa.Integer(), nullable=False, comment='1=대분류, 2=중분류, 3=소분류'),
    sa.Column('name', sa.String(length=200), nullable=False, comment='분류명'),
    sa.Column('code', sa.String(length=50), nullable=False, comment='분류코드'),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('dataset_count', sa.Integer(), nullable=True, comment='연결 데이터셋 수'),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['data_classification.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index('ix_data_class_code', 'data_classification', ['code'], unique=False)
    op.create_index('ix_data_class_parent', 'data_classification', ['parent_id'], unique=False)
    op.create_table('data_grade',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('grade_code', sa.String(length=10), nullable=False, comment='L1/L2/L3'),
    sa.Column('grade_name', sa.String(length=50), nullable=False, comment='비공개/내부공유/공개'),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('access_scope', sa.String(length=200), nullable=True, comment='접근 대상 범위'),
    sa.Column('dataset_count', sa.Integer(), nullable=True),
    sa.Column('anonymize_required', sa.String(length=20), nullable=True, comment='비식별화 필요여부: 필수/선택/불필요'),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('grade_code')
    )
    op.create_table('quality_rule',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rule_name', sa.String(length=200), nullable=False, comment='규칙명'),
    sa.Column('rule_type', sa.String(length=50), nullable=False, comment='COMPLETENESS/VALIDITY/ACCURACY/CONSISTENCY'),
    sa.Column('target_type', sa.String(length=50), nullable=True, comment='DATASET/TABLE/COLUMN'),
    sa.Column('rule_expression', sa.Text(), nullable=True, comment='규칙 로직'),
    sa.Column('severity', sa.String(length=20), nullable=True, comment='ERROR/WARNING/INFO'),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('schedule_cron', sa.String(length=100), nullable=True, comment='배치 스케줄'),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('std_audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('table_name', sa.String(length=100), nullable=False, comment='변경 테이블'),
    sa.Column('record_id', sa.Integer(), nullable=False, comment='변경 레코드 PK'),
    sa.Column('action', sa.String(length=20), nullable=False, comment='INSERT/UPDATE/DELETE'),
    sa.Column('old_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('changed_by', sa.Integer(), nullable=True),
    sa.Column('changed_at', sa.DateTime(), nullable=True),
    sa.Column('change_reason', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_std_audit_date', 'std_audit_log', ['changed_at'], unique=False)
    op.create_index('ix_std_audit_table', 'std_audit_log', ['table_name', 'record_id'], unique=False)
    op.create_table('std_code',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code_group', sa.String(length=100), nullable=False, comment='코드그룹'),
    sa.Column('system_name', sa.String(length=200), nullable=True, comment='시스템명'),
    sa.Column('table_name', sa.String(length=200), nullable=True, comment='테이블명'),
    sa.Column('code_group_name', sa.String(length=200), nullable=False, comment='코드그룹명'),
    sa.Column('code_type', sa.String(length=50), nullable=True, comment='코드구분'),
    sa.Column('seq_no', sa.Integer(), nullable=True, comment='순번'),
    sa.Column('code_id', sa.String(length=100), nullable=False, comment='코드ID'),
    sa.Column('code_value', sa.String(length=200), nullable=True, comment='코드값'),
    sa.Column('code_value_name', sa.String(length=300), nullable=True, comment='코드값명'),
    sa.Column('sort_order', sa.Integer(), nullable=True, comment='정렬순서'),
    sa.Column('parent_code_name', sa.String(length=200), nullable=True, comment='부모코드명'),
    sa.Column('parent_code_value', sa.String(length=200), nullable=True, comment='부모코드값'),
    sa.Column('description', sa.Text(), nullable=True, comment='설명'),
    sa.Column('effective_date', sa.Date(), nullable=True, comment='등록일자'),
    sa.Column('expiration_date', sa.Date(), nullable=True, comment='적용종료일자'),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_std_code_group', 'std_code', ['code_group'], unique=False)
    op.create_index('ix_std_code_id', 'std_code', ['code_id'], unique=False)
    op.create_index('ix_std_code_parent', 'std_code', ['parent_code_name', 'parent_code_value'], unique=False)
    op.create_table('std_compliance_result',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('standard_name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False, comment='단어/용어/도메인/코드'),
    sa.Column('total_items', sa.Integer(), nullable=True),
    sa.Column('passed_items', sa.Integer(), nullable=True),
    sa.Column('failed_items', sa.Integer(), nullable=True),
    sa.Column('compliance_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('checked_at', sa.DateTime(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('std_domain',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('domain_group', sa.String(length=50), nullable=False, comment='도메인그룹'),
    sa.Column('domain_name', sa.String(length=200), nullable=False, comment='도메인명'),
    sa.Column('domain_code', sa.String(length=100), nullable=False, comment='도메인코드명'),
    sa.Column('data_type', sa.String(length=50), nullable=False, comment='데이터유형'),
    sa.Column('length', sa.Integer(), nullable=True, comment='길이'),
    sa.Column('decimal_places', sa.Integer(), nullable=True, comment='소수점'),
    sa.Column('data_format', sa.String(length=200), nullable=True, comment='데이터형식'),
    sa.Column('valid_values', sa.Text(), nullable=True, comment='유효값목록'),
    sa.Column('characteristics', sa.Text(), nullable=True, comment='특징정보'),
    sa.Column('description', sa.Text(), nullable=True, comment='설명'),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain_code')
    )
    op.create_index('ix_std_domain_code', 'std_domain', ['domain_code'], unique=False)
    op.create_index('ix_std_domain_group', 'std_domain', ['domain_group'], unique=False)
    op.create_table('std_request',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('request_type', sa.String(length=20), nullable=False, comment='WORD/DOMAIN/TERM/COMMON_CODE/LIST_CODE'),
    sa.Column('action_type', sa.String(length=20), nullable=False, comment='CREATE/MODIFY/DELETE'),
    sa.Column('request_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='신청 데이터'),
    sa.Column('validation_result', sa.String(length=20), nullable=True, comment='PASS/FAIL/PENDING'),
    sa.Column('validation_message', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True, comment='PENDING/APPROVED/REJECTED'),
    sa.Column('requested_by', sa.Integer(), nullable=True),
    sa.Column('requested_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('review_comment', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('std_term',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('term_name', sa.String(length=300), nullable=False, comment='명칭'),
    sa.Column('english_name', sa.String(length=300), nullable=False, comment='영문명'),
    sa.Column('english_meaning', sa.String(length=500), nullable=True, comment='영문의미'),
    sa.Column('domain_code', sa.String(length=100), nullable=True, comment='도메인코드명 FK'),
    sa.Column('term_classifier', sa.String(length=100), nullable=True, comment='용어특성분류기'),
    sa.Column('domain_group', sa.String(length=50), nullable=True, comment='도메인그룹 (비정규화)'),
    sa.Column('data_type', sa.String(length=50), nullable=True, comment='데이터유형'),
    sa.Column('length', sa.Integer(), nullable=True, comment='길이'),
    sa.Column('decimal_places', sa.Integer(), nullable=True, comment='소수점'),
    sa.Column('data_format', sa.String(length=200), nullable=True, comment='데이터형식'),
    sa.Column('valid_values', sa.Text(), nullable=True, comment='유효값목록'),
    sa.Column('characteristics', sa.Text(), nullable=True, comment='특징정보'),
    sa.Column('description', sa.Text(), nullable=True, comment='설명'),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_std_term_domain', 'std_term', ['domain_code'], unique=False)
    op.create_index('ix_std_term_eng', 'std_term', ['english_name'], unique=False)
    op.create_index('ix_std_term_name', 'std_term', ['term_name'], unique=False)
    op.create_table('std_word',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('word_name', sa.String(length=200), nullable=False, comment='명칭 (한글)'),
    sa.Column('english_name', sa.String(length=200), nullable=False, comment='영문명'),
    sa.Column('english_meaning', sa.String(length=500), nullable=True, comment='영문의미'),
    sa.Column('attr_classifier', sa.String(length=100), nullable=True, comment='속성분류어'),
    sa.Column('synonyms', sa.Text(), nullable=True, comment='동의어'),
    sa.Column('description', sa.Text(), nullable=True, comment='설명'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='ACTIVE/INACTIVE/PENDING'),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_std_word_eng', 'std_word', ['english_name'], unique=False)
    op.create_index('ix_std_word_name', 'std_word', ['word_name'], unique=False)
    op.create_index('ix_std_word_status', 'std_word', ['status'], unique=False)
    op.create_index('uq_std_word', 'std_word', ['word_name', 'english_name'], unique=True)
    op.create_table('classification_sync_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('classification_id', sa.Integer(), nullable=True),
    sa.Column('hub_code', sa.String(length=50), nullable=True),
    sa.Column('portal_code', sa.String(length=50), nullable=True),
    sa.Column('sync_status', sa.String(length=20), nullable=True, comment='MATCH/MISMATCH/NEW/DELETED'),
    sa.Column('synced_at', sa.DateTime(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['classification_id'], ['data_classification.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meta_model',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('model_type', sa.String(length=20), nullable=False, comment='LOGICAL/PHYSICAL'),
    sa.Column('model_name', sa.String(length=300), nullable=False, comment='모델명'),
    sa.Column('system_name', sa.String(length=200), nullable=True, comment='정보시스템'),
    sa.Column('sub_system', sa.String(length=200), nullable=True, comment='서브시스템'),
    sa.Column('db_account', sa.String(length=100), nullable=True, comment='DB계정'),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('version', sa.String(length=20), nullable=True),
    sa.Column('classification_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['classification_id'], ['data_classification.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quality_check_result',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=True),
    sa.Column('dataset_name', sa.String(length=300), nullable=True),
    sa.Column('check_type', sa.String(length=50), nullable=True),
    sa.Column('total_count', sa.Integer(), nullable=True),
    sa.Column('error_count', sa.Integer(), nullable=True),
    sa.Column('score', sa.Numeric(precision=5, scale=2), nullable=True, comment='점수 (%)'),
    sa.Column('executed_at', sa.DateTime(), nullable=True),
    sa.Column('execution_time_ms', sa.Integer(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['rule_id'], ['quality_rule.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meta_model_entity',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('entity_name', sa.String(length=200), nullable=False, comment='테이블명/엔터티명'),
    sa.Column('entity_name_kr', sa.String(length=200), nullable=True, comment='한글명'),
    sa.Column('entity_type', sa.String(length=50), nullable=True, comment='TABLE/VIEW/ENTITY'),
    sa.Column('owner', sa.String(length=100), nullable=True, comment='테이블소유자'),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['meta_model.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meta_model_attribute',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('attr_name', sa.String(length=200), nullable=False, comment='속성명'),
    sa.Column('attr_name_kr', sa.String(length=200), nullable=True, comment='한글명'),
    sa.Column('term_id', sa.Integer(), nullable=True, comment='표준 용어 연결'),
    sa.Column('domain_id', sa.Integer(), nullable=True, comment='도메인 연결'),
    sa.Column('data_type', sa.String(length=50), nullable=True),
    sa.Column('length', sa.Integer(), nullable=True),
    sa.Column('decimal_places', sa.Integer(), nullable=True),
    sa.Column('is_pk', sa.Boolean(), nullable=True),
    sa.Column('is_nullable', sa.Boolean(), nullable=True),
    sa.Column('default_value', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['domain_id'], ['std_domain.id'], ),
    sa.ForeignKeyConstraint(['entity_id'], ['meta_model_entity.id'], ),
    sa.ForeignKeyConstraint(['term_id'], ['std_term.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('meta_model_attribute')
    op.drop_table('meta_model_entity')
    op.drop_table('quality_check_result')
    op.drop_table('meta_model')
    op.drop_table('classification_sync_log')
    op.drop_index('uq_std_word', table_name='std_word')
    op.drop_index('ix_std_word_status', table_name='std_word')
    op.drop_index('ix_std_word_name', table_name='std_word')
    op.drop_index('ix_std_word_eng', table_name='std_word')
    op.drop_table('std_word')
    op.drop_index('ix_std_term_name', table_name='std_term')
    op.drop_index('ix_std_term_eng', table_name='std_term')
    op.drop_index('ix_std_term_domain', table_name='std_term')
    op.drop_table('std_term')
    op.drop_table('std_request')
    op.drop_index('ix_std_domain_group', table_name='std_domain')
    op.drop_index('ix_std_domain_code', table_name='std_domain')
    op.drop_table('std_domain')
    op.drop_table('std_compliance_result')
    op.drop_index('ix_std_code_parent', table_name='std_code')
    op.drop_index('ix_std_code_id', table_name='std_code')
    op.drop_index('ix_std_code_group', table_name='std_code')
    op.drop_table('std_code')
    op.drop_index('ix_std_audit_table', table_name='std_audit_log')
    op.drop_index('ix_std_audit_date', table_name='std_audit_log')
    op.drop_table('std_audit_log')
    op.drop_table('quality_rule')
    op.drop_table('data_grade')
    op.drop_index('ix_data_class_parent', table_name='data_classification')
    op.drop_index('ix_data_class_code', table_name='data_classification')
    op.drop_table('data_classification')
    # ### end Alembic commands ###
